
# Configuration for redis databases. We have three databases: one for
# celery tasks, one for Flask sessions, and one for the "metadb",
# which basically links together jobs, input files, and schemas. For
# each one, we need to specify host, port and database number.

session_host: localhost
session_port: 6379
session_db: 2

metadb_host: localhost
metadb_port: 6379
metadb_db: 2

celery_host: localhost
celery_port: 6379
celery_db: 2

metadb_dir: /var/padedb

