
# Configuration for redis databases. We have three databases: one for
# celery tasks, one for Flask sessions, and one for the "metadb",
# which basically links together jobs, input files, and schemas. For
# each one, we need to specify host, port and database number.

redis :
  celery: 
    host: localhost
    port: 6379
    db: 1

  session: 
    host: localhost     
    port: 6379
    db: 2

  metadb: 
    host: localhost     
    port: 6379
    db: 3

metadb_dir: padedb
